AWSTemplateFormatVersion: 2010-09-09
Description: CloudFormation Template

#Metadata:

#Parameters:

#Rules:

#Mappings:

#Conditions:

#Transform:

Resources:
    DynamoDBTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: MyDynamoDBTable
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        
# Outputs:
